### ISSUE TITLE
404 Not found on issue tracker link

### ISSUE THREAD

**Issue by luilver** [edgecase/ruby_koans#19]
### Steps to reproduce

* On this section:

    https://github.com/edgecase/ruby_koans#label-Other+stuff

* When clicking 

    https://www.pivotaltracker.com/projects/48111

* Gets this

    ![image](https://user-images.githubusercontent.com/681020/85861508-7981a500-b78e-11ea-8de3-90f6a5458e85.png)

**Comment by tonywok** [comment]
I'm going to go ahead and remove that link as it's looooong gone :)

All issues should be going through GitHub at this point. Remember when that wasn't a thing? Wildcats.

**Comment by tonywok** [comment]
Fixed! Thank you :)
