### ISSUE TITLE
issue matching about_methods

### ISSUE THREAD

**Issue by georgettica** [edgecase/ruby_koans#22]
when running thought the `path_to_enlightment` I got to this and what I saw:
```ruby
assert_match(/__/, exception.message)
```
and the result of this test is:
```
The answers you seek...
  Expected "wrong number of arguments (given 0, expected 2)" to match /__/

Please meditate on the following code:
  **koans/about_methods.rb:39:in `test_calling_global_methods_with_wrong_number_of_arguments'
```

and I think the result should be:
```ruby
assert_match(exception.message, /wrong number of arguments/)
```

if I am incorrect or misguided please notify me.

link to assumed code change 
https://github.com/edgecase/ruby_koans/blob/7d152b8afc0a39c5b3917e2f14512edac3945e88/src/about_methods.rb#L49

**Comment by georgettica** [comment]
@mdoel maybe you can help me with the proccess of changing this or is this the right place to change"

**Comment by mdoel** [comment]
@georgettica - try switching around your arguments. The assert is looking for the regex first.

```ruby
assert_match(/wrong number of arguments/, exception.message)
```

**Comment by georgettica** [comment]
yeah, I guess the regex didn't work for me and I thought it was an error with the koans. thanks for replying! will close
