### ISSUE TITLE
About Open Classes: `Integer#even?` is already a method

### ISSUE THREAD

**Issue by raghubetina** [edgecase/ruby_koans#26]
In the About Open Classes koan, [we re-open the built-in class `Integer` to define the `even?` method](https://github.com/edgecase/ruby_koans/blob/7d152b8afc0a39c5b3917e2f14512edac3945e88/src/about_open_classes.rb#L33); but I found it a bit confusing, since `even?` is already defined for `Integer`:

https://ruby-doc.org/core-2.6/Integer.html#method-i-even-3F

If the idea is to demonstrate that we can add new methods to built-in classes, perhaps it would be more clear if we define something like `Integer#multiple_of_three?` in this koan?

**Comment by tonywok** [comment]
Ah, that's a really good point. Care to add a PR? Otherwise I can probably get to it this week. Thanks for pointing this out!

**Comment by tonywok** [comment]
Fixed in 561965bb6a112a15955a96e1de62c4671d13ed2f
