### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Tom-H-L** [edgecase/ruby_koans#36]
http://rubykoans.com/
 
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by tonywok** [comment]
😱 Missed this in my notifications. I'll try to figure out who owns the heroku account.

I think we should convert this to a static site, removing the need for heroku. I'll try to find some time or this in the coming weeks.

**Comment by tonywok** [comment]
Website is up!
