### ISSUE TITLE
Randomly fails on random file in ruby 3.2.2 on windows

### ISSUE THREAD

**Issue by zehrenz** [edgecase/ruby_koans#40]
I unzipped the download file, fixed the "exists -> exist" problem and ran rake. Running rake five times in a row has one work as expected. The others throw a seg fault from a random file (most often about_true_and_false) full output below. This random failing behavior also happened when following instructions in the main readme.

C:/Ruby32-x64/bin/ruby.exe path_to_enlightenment.rb
C:/Users/jlpeters/Documents/CodeLearning/ruby-koans/about_true_and_false.rb: [BUG] Segmentation fault
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0035 e:000034 CFUNC  :method_missing
c:0006 p:---- s:0032 e:000031 CFUNC  :set_encoding
c:0005 p:---- s:0029 e:000028 DUMMY  [FINISH]
c:0004 p:---- s:0026 e:000025 CFUNC  :require
c:0003 p:0107 s:0021 e:000020 METHOD <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85
c:0002 p:0022 s:0006 e:000005 EVAL   path_to_enlightenment.rb:6 [FINISH]
c:0001 p:0000 s:0003 E:0012a0 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
path_to_enlightenment.rb:6:in `<main>'
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `set_encoding'
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `method_missing'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0x14) [0x00007ffd595cecd4]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x8e) [0x00007ffd56ec9c2e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_bugreport+0x256) [0x00007ffcb9fd2ee6]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_bug_for_fatal_signal+0x80) [0x00007ffcb9dd05b0]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_shape_memsize+0x542) [0x00007ffcb9f1e502]
 [0x00007ff77f061e22]
C:\WINDOWS\System32\ucrtbase.dll(_C_specific_handler+0xa0) [0x00007ffd56b07f30]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x12f) [0x00007ffd595d3cff]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlFindCharInUnicodeString+0xa96) [0x00007ffd5954e456]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007ffd595d2cee]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_gc_disable_no_rest+0x344) [0x00007ffcb9df7774]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_gc_writebarrier+0x8e) [0x00007ffcb9df79de]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_iseqw_new+0x7b) [0x00007ffcb9e45eeb]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_nomethod_err_new+0xda) [0x00007ffcb9dd0e6a]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_pop_cfunc_frame+0x263) [0x00007ffcb9fafe13]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_pop_cfunc_frame+0x356) [0x00007ffcb9faff06]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_proc+0x1eb) [0x00007ffcb9fbb73b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_obj_respond_to+0x3a9) [0x00007ffcb9fbf239]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_proc+0x52e) [0x00007ffcb9fbba7e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_call_kw+0x20c) [0x00007ffcb9fca18c]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vrescue2+0x16e) [0x00007ffcb9ddbb5e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_rescue2+0x2a) [0x00007ffcb9ddbdfa]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_funcall_basic_kw+0x378) [0x00007ffcb9fbd788]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_funcall_basic_kw+0x657) [0x00007ffcb9fbda67]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_funcall+0x1a) [0x00007ffcb9fbdbda]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_check_convert_type_with_id+0x49) [0x00007ffcb9e79cb9]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_io_close+0x125a) [0x00007ffcb9e2271a]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_io_check_closed+0xe5) [0x00007ffcb9e257d5]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_proc+0x1eb) [0x00007ffcb9fbb73b]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_eval_cmd_kw+0x5a3) [0x00007ffcb9fc0623]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_funcallv+0x11) [0x00007ffcb9fc0871]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(weak.Init_extra_exts.ruby_push_include+0x36a) [0x00007ffcb9f1920a]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_ensure+0x1dc) [0x00007ffcb9ddc2dc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_parser_load_file+0xf1) [0x00007ffcb9f1ae91]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_resolve_feature_path+0x2dc4) [0x00007ffcb9e4cfb4]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_f_require+0x3f) [0x00007ffcb9e4d14f]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_error_arity+0x147) [0x00007ffcb9fa8b27]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_invoke_bmethod+0x190e) [0x00007ffcb9fb7e2e]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_opt_newarray_max+0x3ec) [0x00007ffcb9fc44cc]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_vm_exec+0x11c) [0x00007ffcb9fb560c]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(rb_call_end_proc+0x130) [0x00007ffcb9dd51f0]
C:\Ruby32-x64\bin\x64-ucrt-ruby320.dll(ruby_run_node+0xa5) [0x00007ffcb9ddafd5]
 [0x00007ff77f062a20]
 [0x00007ff77f0612ee]
 [0x00007ff77f061406]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x1d) [0x00007ffd575526bd]

-- Other runtime information -----------------------------------------------

* Loaded script: path_to_enlightenment.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb
    6 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/encdb.so
    7 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/trans/transdb.so
    8 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/rbconfig.rb
    9 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/compatibility.rb
   10 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/defaults.rb
   11 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/deprecate.rb
   12 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/errors.rb
   13 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/unknown_command_spell_checker.rb
   14 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/exceptions.rb
   15 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/basic_specification.rb
   16 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/stub_specification.rb
   17 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/platform.rb
   18 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/util/list.rb
   19 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/version.rb
   20 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/requirement.rb
   21 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/specification.rb
   22 C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/singleton.rb
   23 C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime.rb
   24 C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb
   25 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/win32/dll_directory.so
   26 C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/dll_directory.rb
   27 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/utf_16le.so
   28 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/enc/trans/utf_16_32.so
   29 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/text.rb
   30 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/user_interaction.rb
   31 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/etc.so
   32 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/config_file.rb
   33 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/defaults/operating_system.rb
   34 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/util.rb
   35 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/dependency.rb
   36 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_gem.rb
   37 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/monitor.so
   38 C:/Ruby32-x64/lib/ruby/3.2.0/monitor.rb
   39 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems.rb
   40 C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/path_support.rb
   41 C:/Ruby32-x64/lib/ruby/3.2.0/error_highlight/version.rb
   42 C:/Ruby32-x64/lib/ruby/3.2.0/error_highlight/base.rb
   43 C:/Ruby32-x64/lib/ruby/3.2.0/error_highlight/formatter.rb
   44 C:/Ruby32-x64/lib/ruby/3.2.0/error_highlight/core_ext.rb
   45 C:/Ruby32-x64/lib/ruby/3.2.0/error_highlight.rb
   46 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/version.rb
   47 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/core_ext/name_error.rb
   48 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/levenshtein.rb
   49 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/jaro_winkler.rb
   50 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checker.rb
   51 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   52 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   53 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/name_error_checkers.rb
   54 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/method_name_checker.rb
   55 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/key_error_checker.rb
   56 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/null_checker.rb
   57 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/tree_spell_checker.rb
   58 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/require_path_checker.rb
   59 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/spell_checkers/pattern_key_name_checker.rb
   60 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean/formatter.rb
   61 C:/Ruby32-x64/lib/ruby/3.2.0/did_you_mean.rb
   62 C:/Ruby32-x64/lib/ruby/3.2.0/syntax_suggest/core_ext.rb
   63 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/win32console-1.3.2/lib/Console_ext.so
   64 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/win32console-1.3.2/lib/Win32/Console.rb
   65 C:/Ruby32-x64/lib/ruby/3.2.0/x64-mingw-ucrt/fiddle.so
   66 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/closure.rb
   67 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/function.rb
   68 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/version.rb
   69 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle.rb
   70 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/value.rb
   71 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/pack.rb
   72 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/struct.rb
   73 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/cparser.rb
   74 C:/Ruby32-x64/lib/ruby/3.2.0/fiddle/import.rb
   75 C:/Ruby32-x64/lib/ruby/3.2.0/win32/registry.rb
   76 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/win32console-1.3.2/lib/Win32/Console/ANSI.rb
   77 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/win32console-1.3.2/lib/win32console.rb
   78 C:/Users/jlpeters/Documents/CodeLearning/ruby-koans/neo.rb
   79 C:/Users/jlpeters/Documents/CodeLearning/ruby-koans/about_asserts.rb

rake aborted!
Command failed with status (3): [C:/Ruby32-x64/bin/ruby.exe path_to_enlight...]
C:/Users/jlpeters/Documents/CodeLearning/ruby-koans/Rakefile:10:in `block in <top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)

**Comment by tonywok** [comment]
Thank you for the detailed error message. Closing as duplicate.
