### ISSUE TITLE
Segmentation fault / bus error in about_symbols.rb

### ISSUE THREAD

**Issue by JakubSarnik** [edgecase/ruby_koans#43]
There are strange crashes when running the koans emanating from the file `about_symbols.rb`. The problematic piece of code is the  block on lines 36-43:

    in_ruby_version("mri") do
      RubyConstant = "What is the sound of one hand clapping?"
      def test_constants_become_symbols
        all_symbols_as_strings = Symbol.all_symbols.map { |x| x.to_s }

        assert_equal __, all_symbols_as_strings.include?(__)
      end
    end

Specifically, the error occurs on the line 39 (that sets the variable `all_symbols_as_string`). I attach a rake output and ruby diagnostic report from one instance of the crash, manifesting as a segmentation fault. This failure is also sometimes reported as a bus error.

I use the state of the repository as in commit [3bb8d5d](https://github.com/edgecase/ruby_koans/commit/3bb8d5da68c107cbf8341ce4f4e41dfe98b76802) on macOS 13.2.1 (22D68) (on x86-64 Intel).

[Rake output](https://github.com/edgecase/ruby_koans/files/11413539/koans_rake_output.txt)
[Ruby diagnostic report](https://github.com/edgecase/ruby_koans/files/11413541/ruby-report.txt)

**Comment by anthonyjara7** [comment]
Any updates on this issue? Currently experiencing the same thing

**Comment by JakubSarnik** [comment]
You can work around it by commenting out pieces of the code that cause these bugs (they are much more frequent than this specific issue, as I found out later), and few instances go away on their own if you simply make the tests pass or run rake several times over and over. It seems to me that the whole project is more or less broken at the moment.

**Comment by sbditto85** [comment]
I used `asdf` to pin my version of ruby to 3.0.0 and so far it seems to work. (I'm about 35% done)

**Comment by tonywok** [comment]
Apologies for the state of things -- it has certainly been a bit neglected. I'll try to sort this out as I get some time 🤞

**Comment by tonywok** [comment]
I've pulled down the recently released zip and run it against 3.2.2 successfully. I'm curious if it would resolve your issue.

Unfortunately I don't believe there's any kind of functionality to migrate from one version of ruby koans that you've edited to another (aside from copying files or starting over).

edit: Actually, iirc you can manipulate the `.path_progress` file.

**Comment by tonywok** [comment]
Thank you for the detailed issue. Closing as duplicate and hope to resolve soon.
