### ISSUE TITLE
Randomly fails with a segfault on mac with ruby 3.2.2

### ISSUE THREAD

**Issue by michalDob** [edgecase/ruby_koans#45]
koans/neo.rb:122: [BUG] Segmentation fault at 0x0000000200000205
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0017 p:0012 s:0077 e:000073 METHOD /home/bento/ruby_koans/koans/neo.rb:122
c:0016 p:0010 s:0069 e:000068 METHOD /home/bento/ruby_koans/koans/neo.rb:115
c:0015 p:0007 s:0063 e:000062 METHOD (eval):1
c:0014 p:0058 s:0058 e:000056 METHOD /home/bento/ruby_koans/koans/neo.rb:244
c:0013 p:0008 s:0052 e:000051 BLOCK  /home/bento/ruby_koans/koans/neo.rb:519
c:0012 p:0031 s:0048 e:000047 BLOCK  /home/bento/ruby_koans/koans/neo.rb:530 [FINISH]
c:0011 p:---- s:0043 e:000042 CFUNC  :each
c:0010 p:0007 s:0039 e:000038 BLOCK  /home/bento/ruby_koans/koans/neo.rb:528 [FINISH]
c:0009 p:---- s:0034 e:000033 IFUNC
c:0008 p:---- s:0031 e:000030 CFUNC  :each
c:0007 p:---- s:0028 e:000027 CFUNC  :each_with_index
c:0006 p:0010 s:0024 e:000023 BLOCK  /home/bento/ruby_koans/koans/neo.rb:527 [FINISH]
c:0005 p:---- s:0020 e:000019 CFUNC  :catch
c:0004 p:0006 s:0015 e:000014 METHOD /home/bento/ruby_koans/koans/neo.rb:525
c:0003 p:0010 s:0011 e:000010 METHOD /home/bento/ruby_koans/koans/neo.rb:518
c:0002 p:0013 s:0006 e:000005 BLOCK  /home/bento/ruby_koans/koans/neo.rb:540 [FINISH]
c:0001 p:0000 s:0003 E:0004d0 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/bento/ruby_koans/koans/neo.rb:540:in `block in <top (required)>'
/home/bento/ruby_koans/koans/neo.rb:518:in `walk'
/home/bento/ruby_koans/koans/neo.rb:525:in `each_step'
/home/bento/ruby_koans/koans/neo.rb:525:in `catch'
/home/bento/ruby_koans/koans/neo.rb:527:in `block in each_step'
/home/bento/ruby_koans/koans/neo.rb:527:in `each_with_index'
/home/bento/ruby_koans/koans/neo.rb:527:in `each'
/home/bento/ruby_koans/koans/neo.rb:528:in `block (2 levels) in each_step'
/home/bento/ruby_koans/koans/neo.rb:528:in `each'
/home/bento/ruby_koans/koans/neo.rb:530:in `block (3 levels) in each_step'
/home/bento/ruby_koans/koans/neo.rb:519:in `block in walk'
/home/bento/ruby_koans/koans/neo.rb:244:in `observe'
(eval):1:in `green'
/home/bento/ruby_koans/koans/neo.rb:115:in `colorize'
/home/bento/ruby_koans/koans/neo.rb:122:in `color'

-- Machine register context ------------------------------------------------
 RIP: 0x000055e7af9168ef RBP: 0x000055e7b08ad8e0 RSP: 0x00007fffbb45acf0
 RAX: 0x0000000000000015 RBX: 0x000055e7b0512b38 RCX: 0x0000000200000205
 RDX: 0x000000000000056c RDI: 0x000055e7b05127e0 RSI: 0x000000000000002c
  R8: 0x0000000000000001  R9: 0x0000000000000020 R10: 0x00007f4211f8ffe8
 R11: 0x000000000000000c R12: 0x000055e7b05127e0 R13: 0x000055e7b0512c30
 R14: 0x00007fffbb45b060 R15: 0x0000000000000000 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_print_backtrace+0x11) [0x55e7afb0061d] vm_dump.c:785
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_bugreport) vm_dump.c:1080
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_bug_for_fatal_signal+0xec) [0x55e7afbabfbc] error.c:813
/home/bento/.rbenv/versions/3.2.2/bin/ruby(sigsegv+0x4d) [0x55e7afa5111d] signal.c:964
/lib/x86_64-linux-gnu/libpthread.so.0(__restore_rt+0x0) [0x7f42125f3420]
/home/bento/.rbenv/versions/3.2.2/bin/ruby(RVALUE_MARKED+0x34) [0x55e7af9168ef] gc.c:1656
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_mark_set) gc.c:6930
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_mark_ptr) gc.c:7044
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_mark_children+0x817) [0x55e7af918597] gc.c:7317
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_mark_stacked_objects+0xe) [0x55e7af919aa9] gc.c:7437
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_mark_stacked_objects_all) gc.c:7477
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_marks_rest) gc.c:8675
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_marks+0x37) [0x55e7af91aa79] gc.c:8716
/home/bento/.rbenv/versions/3.2.2/bin/ruby(gc_start) gc.c:9547
/home/bento/.rbenv/versions/3.2.2/bin/ruby(heap_prepare+0x52) [0x55e7af91b653] gc.c:2431
/home/bento/.rbenv/versions/3.2.2/bin/ruby(heap_next_free_page) gc.c:2672
/home/bento/.rbenv/versions/3.2.2/bin/ruby(newobj_alloc) gc.c:2780
/home/bento/.rbenv/versions/3.2.2/bin/ruby(newobj_of0+0x64) [0x55e7af91e3b8] gc.c:2876
/home/bento/.rbenv/versions/3.2.2/bin/ruby(newobj_of) gc.c:2896
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_wb_protected_newobj_of) gc.c:2918
/home/bento/.rbenv/versions/3.2.2/bin/ruby(str_alloc_embed+0x12) [0x55e7afa6b27a] string.c:894
/home/bento/.rbenv/versions/3.2.2/bin/ruby(str_duplicate) string.c:1827
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_str_resurrect+0x5) [0x55e7afa7c59b] string.c:1843
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_str_concat_literals) string.c:3344
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_exec_core+0x2170) [0x55e7afaf4300] insns.def:405
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_exec+0x640) [0x55e7afae2db0] vm.c:2383
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_yield+0x25e) [0x55e7afae7c2e] vm.c:1398
/home/bento/.rbenv/versions/3.2.2/bin/ruby(RB_FL_TEST_RAW+0x0) [0x55e7afb1195c] array.c:2740
/home/bento/.rbenv/versions/3.2.2/bin/ruby(RB_FL_ANY_RAW) ./include/ruby/internal/fl_type.h:552
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_array_len) ./include/ruby/internal/core/rarray.h:321
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_ary_each) array.c:2739
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_cfunc_with_frame+0x128) [0x55e7afad6158] vm_insnhelper.c:3268
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_sendish+0x0) [0x55e7afaf2439] vm_insnhelper.c:5080
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_exec_core) insns.def:801
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_exec+0x18e) [0x55e7afae28fe] vm.c:2374
/home/bento/.rbenv/versions/3.2.2/bin/ruby(each_with_index_i+0x91) [0x55e7afb9b5b1] enum.c:2745
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_pop_frame+0x0) [0x55e7afae0f82] vm_insnhelper.c:4288
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_yield_with_cfunc) vm_insnhelper.c:4289
/home/bento/.rbenv/versions/3.2.2/bin/ruby(invoke_block_from_c_bh+0x24) [0x55e7afae7d33] vm.c:1477
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_yield_with_cref) vm.c:1509
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_yield) vm.c:1517
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_yield_0) vm_eval.c:1348
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_yield) vm_eval.c:1364
/home/bento/.rbenv/versions/3.2.2/bin/ruby(RB_FL_TEST_RAW+0x0) [0x55e7afb1195c] array.c:2740
/home/bento/.rbenv/versions/3.2.2/bin/ruby(RB_FL_ANY_RAW) ./include/ruby/internal/fl_type.h:552
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_array_len) ./include/ruby/internal/core/rarray.h:321
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_ary_each) array.c:2739
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_cfp_consistent_p+0x0) [0x55e7afaea3ef] vm_eval.c:150
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call0_cfunc_with_frame) vm_eval.c:152
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call0_cfunc) vm_eval.c:164
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call0_body) vm_eval.c:210
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_call0+0x223) [0x55e7afaed623] vm_eval.c:87
/home/bento/.rbenv/versions/3.2.2/bin/ruby(iterate_method+0x3b) [0x55e7afaee24b] vm_eval.c:877
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_iterate0+0x109) [0x55e7afadd619] vm_eval.c:1532
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_block_call+0x76) [0x55e7afadd986] vm_eval.c:1564
/home/bento/.rbenv/versions/3.2.2/bin/ruby(enum_each_with_index+0x4c) [0x55e7afb96dac] enum.c:2783
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_cfunc_with_frame+0x128) [0x55e7afad6158] vm_insnhelper.c:3268
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_method_each_type+0x79) [0x55e7afae39d9] vm_insnhelper.c:3920
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_method+0xc4) [0x55e7afae44e4] vm_insnhelper.c:4070
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_sendish+0x0) [0x55e7afaf2439] vm_insnhelper.c:5080
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_exec_core) insns.def:801
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_exec+0x18e) [0x55e7afae28fe] vm.c:2374
/home/bento/.rbenv/versions/3.2.2/bin/ruby(catch_i+0x2c7) [0x55e7afae6c87] vm.c:1398
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_catch_protect+0xf2) [0x55e7afaddb42] vm_eval.c:2393
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_catch_obj+0x1f) [0x55e7afaddd94] vm_eval.c:2419
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_f_catch) vm_eval.c:2369
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_cfunc_with_frame+0x128) [0x55e7afad6158] vm_insnhelper.c:3268
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_method_each_type+0x79) [0x55e7afae39d9] vm_insnhelper.c:3920
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_call_method+0xc4) [0x55e7afae44e4] vm_insnhelper.c:4070
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_sendish+0x0) [0x55e7afaf2439] vm_insnhelper.c:5080
/home/bento/.rbenv/versions/3.2.2/bin/ruby(vm_exec_core) insns.def:801
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_exec+0x18e) [0x55e7afae28fe] vm.c:2374
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_vm_invoke_proc+0x33) [0x55e7afaea223] vm.c:1603
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_proc_call_kw+0x28) [0x55e7af9e9815] proc.c:995
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_proc_call) proc.c:1005
/home/bento/.rbenv/versions/3.2.2/bin/ruby(exec_end_procs_chain+0x43) [0x55e7af8f467d] eval_jump.c:105
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_ec_exec_end_proc) eval_jump.c:120
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_ec_teardown+0xd5) [0x55e7af8f4895] eval.c:159
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_ec_cleanup+0x152) [0x55e7af8f4a92] eval.c:212
/home/bento/.rbenv/versions/3.2.2/bin/ruby(ruby_run_node+0x59) [0x55e7af8f5439] eval.c:330
/home/bento/.rbenv/versions/3.2.2/bin/ruby(rb_main+0x21) [0x55e7af8effc7] ./main.c:38
/home/bento/.rbenv/versions/3.2.2/bin/ruby(main) ./main.c:57
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f4212411083]
[0x55e7af8f001e]

-- Other runtime information -----------------------------------------------

* Process memory map:

55e7af8bc000-55e7af8eb000 r--p 00000000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
55e7af8eb000-55e7afbb8000 r-xp 0002f000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
55e7afbb8000-55e7afcf0000 r--p 002fc000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
55e7afcf0000-55e7afcfa000 r--p 00433000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
55e7afcfa000-55e7afcfb000 rw-p 0043d000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
55e7afcfb000-55e7afd0d000 rw-p 00000000 00:00 0
55e7b050e000-55e7b08d5000 rw-p 00000000 00:00 0                          [heap]
7f420b12f000-7f420b31f000 r--s 00000000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f420b31f000-7f420b346000 r--s 00000000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f420b346000-7f420d74e000 r--s 00000000 103:01 4976823                   /home/bento/.rbenv/versions/3.2.2/bin/ruby
7f420d74e000-7f420d751000 r--p 00000000 103:01 4842                      /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f420d751000-7f420d763000 r-xp 00003000 103:01 4842                      /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f420d763000-7f420d767000 r--p 00015000 103:01 4842                      /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f420d767000-7f420d768000 r--p 00018000 103:01 4842                      /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f420d768000-7f420d769000 rw-p 00019000 103:01 4842                      /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f420d780000-7f420d9b0000 rw-p 00000000 00:00 0
7f420d9c0000-7f420da90000 rw-p 00000000 00:00 0
7f420da90000-7f420da91000 ---p 00000000 00:00 0
7f420da91000-7f420db32000 rw-p 00000000 00:00 0
7f420db32000-7f420db33000 ---p 00000000 00:00 0
7f420db33000-7f420dbd4000 rw-p 00000000 00:00 0
7f420dbd4000-7f420dbd5000 ---p 00000000 00:00 0
7f420dbd5000-7f420dc76000 rw-p 00000000 00:00 0
7f420dc76000-7f420dc77000 ---p 00000000 00:00 0
7f420dc77000-7f420dd18000 rw-p 00000000 00:00 0
7f420dd18000-7f420dd19000 ---p 00000000 00:00 0
7f420dd19000-7f420ddba000 rw-p 00000000 00:00 0
7f420ddba000-7f420ddbb000 ---p 00000000 00:00 0
7f420ddbb000-7f420de5c000 rw-p 00000000 00:00 0
7f420de5c000-7f420de5d000 ---p 00000000 00:00 0
7f420de5d000-7f420defe000 rw-p 00000000 00:00 0
7f420defe000-7f420deff000 ---p 00000000 00:00 0
7f420deff000-7f420dfa0000 rw-p 00000000 00:00 0
7f420dfa0000-7f420dfa1000 ---p 00000000 00:00 0
7f420dfa1000-7f420e042000 rw-p 00000000 00:00 0
7f420e042000-7f420e043000 ---p 00000000 00:00 0
7f420e043000-7f420e0e4000 rw-p 00000000 00:00 0
7f420e0e4000-7f420e0e5000 ---p 00000000 00:00 0
7f420e0e5000-7f420e186000 rw-p 00000000 00:00 0
7f420e186000-7f420e187000 ---p 00000000 00:00 0
7f420e187000-7f420e228000 rw-p 00000000 00:00 0
7f420e228000-7f420e229000 ---p 00000000 00:00 0
7f420e229000-7f420e2ca000 rw-p 00000000 00:00 0
7f420e2ca000-7f420e2cb000 ---p 00000000 00:00 0
7f420e2cb000-7f420e36c000 rw-p 00000000 00:00 0
7f420e36c000-7f420e36d000 ---p 00000000 00:00 0
7f420e36d000-7f420e40e000 rw-p 00000000 00:00 0
7f420e40e000-7f420e40f000 ---p 00000000 00:00 0
7f420e40f000-7f420e4b0000 rw-p 00000000 00:00 0
7f420e4b0000-7f420e4b1000 ---p 00000000 00:00 0
7f420e4b1000-7f420e552000 rw-p 00000000 00:00 0
7f420e552000-7f420e553000 ---p 00000000 00:00 0
7f420e553000-7f420e5f4000 rw-p 00000000 00:00 0
7f420e5f4000-7f420e5f5000 ---p 00000000 00:00 0
7f420e5f5000-7f420e696000 rw-p 00000000 00:00 0
7f420e696000-7f420e697000 ---p 00000000 00:00 0
7f420e697000-7f420e738000 rw-p 00000000 00:00 0
7f420e738000-7f420e739000 ---p 00000000 00:00 0
7f420e739000-7f420e7da000 rw-p 00000000 00:00 0
7f420e7da000-7f420e7db000 ---p 00000000 00:00 0
7f420e7db000-7f420e87c000 rw-p 00000000 00:00 0
7f420e87c000-7f420e87d000 ---p 00000000 00:00 0
7f420e87d000-7f420e91e000 rw-p 00000000 00:00 0
7f420e91e000-7f420e91f000 ---p 00000000 00:00 0
7f420e91f000-7f420e9c0000 rw-p 00000000 00:00 0
7f420e9c0000-7f420e9c1000 ---p 00000000 00:00 0
7f420e9c1000-7f420ea62000 rw-p 00000000 00:00 0
7f420ea62000-7f420ea63000 ---p 00000000 00:00 0
7f420ea63000-7f420eb04000 rw-p 00000000 00:00 0
7f420eb04000-7f420eb05000 ---p 00000000 00:00 0
7f420eb05000-7f420eba6000 rw-p 00000000 00:00 0
7f420eba6000-7f420eba7000 ---p 00000000 00:00 0
7f420eba7000-7f420ec48000 rw-p 00000000 00:00 0
7f420ec48000-7f420ec49000 ---p 00000000 00:00 0
7f420ec49000-7f420ecea000 rw-p 00000000 00:00 0
7f420ecea000-7f420eceb000 ---p 00000000 00:00 0
7f420eceb000-7f420ed8c000 rw-p 00000000 00:00 0
7f420ed8c000-7f420ed8d000 ---p 00000000 00:00 0
7f420ed8d000-7f420ee2e000 rw-p 00000000 00:00 0
7f420ee2e000-7f420ee2f000 ---p 00000000 00:00 0
7f420ee2f000-7f420ef00000 rw-p 00000000 00:00 0
7f420ef06000-7f4211fd0000 rw-p 00000000 00:00 0
7f4211fd2000-7f42120d3000 rw-p 00000000 00:00 0
7f42120d3000-7f4212105000 r--p 00000000 103:01 6156                      /usr/lib/locale/C.UTF-8/LC_CTYPE
7f4212105000-7f42123eb000 r--p 00000000 103:01 6150                      /usr/lib/locale/locale-archive
7f42123eb000-7f42123ed000 rw-p 00000000 00:00 0
7f42123ed000-7f421240f000 r--p 00000000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f421240f000-7f4212587000 r-xp 00022000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f4212587000-7f42125d5000 r--p 0019a000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f42125d5000-7f42125d9000 r--p 001e7000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f42125d9000-7f42125db000 rw-p 001eb000 103:01 4762                      /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f42125db000-7f42125df000 rw-p 00000000 00:00 0
7f42125df000-7f42125e5000 r--p 00000000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f42125e5000-7f42125f6000 r-xp 00006000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f42125f6000-7f42125fc000 r--p 00017000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f42125fc000-7f42125fd000 r--p 0001c000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f42125fd000-7f42125fe000 rw-p 0001d000 103:01 4821                      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f42125fe000-7f4212604000 rw-p 00000000 00:00 0
7f4212604000-7f4212611000 r--p 00000000 103:01 4764                      /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f4212611000-7f42126b8000 r-xp 0000d000 103:01 4764                      /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f42126b8000-7f4212751000 r--p 000b4000 103:01 4764                      /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f4212751000-7f4212752000 r--p 0014c000 103:01 4764                      /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f4212752000-7f4212753000 rw-p 0014d000 103:01 4764                      /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f4212753000-7f4212755000 r--p 00000000 103:01 3510                      /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4212755000-7f421276a000 r-xp 00002000 103:01 3510                      /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f421276a000-7f4212784000 r--p 00017000 103:01 3510                      /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4212784000-7f4212785000 r--p 00030000 103:01 3510                      /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4212785000-7f4212786000 rw-p 00031000 103:01 3510                      /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f4212786000-7f421278e000 rw-p 00000000 00:00 0
7f421278e000-7f421278f000 r--p 00000000 103:01 4763                      /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f421278f000-7f4212791000 r-xp 00001000 103:01 4763                      /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f4212791000-7f4212792000 r--p 00003000 103:01 4763                      /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f4212792000-7f4212793000 r--p 00003000 103:01 4763                      /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f4212793000-7f4212794000 rw-p 00004000 103:01 4763                      /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f4212794000-7f421279e000 r--p 00000000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f421279e000-7f42127fe000 r-xp 0000a000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f42127fe000-7f4212815000 r--p 0006a000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f4212815000-7f4212816000 ---p 00081000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f4212816000-7f4212817000 r--p 00081000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f4212817000-7f4212818000 rw-p 00082000 103:01 3808                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0
7f4212818000-7f421281a000 r--p 00000000 103:01 4844                      /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f421281a000-7f421281e000 r-xp 00002000 103:01 4844                      /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f421281e000-7f4212820000 r--p 00006000 103:01 4844                      /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f4212820000-7f4212821000 r--p 00007000 103:01 4844                      /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f4212821000-7f4212822000 rw-p 00008000 103:01 4844                      /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f4212822000-7f4212824000 r--p 00000000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f4212824000-7f4212835000 r-xp 00002000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f4212835000-7f421283b000 r--p 00013000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f421283b000-7f421283c000 ---p 00019000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f421283c000-7f421283d000 r--p 00019000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f421283d000-7f421283e000 rw-p 0001a000 103:01 3874                      /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7f421283e000-7f421283f000 r--p 00000000 103:01 4976912                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/monitor.so
7f421283f000-7f4212840000 r-xp 00001000 103:01 4976912                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/monitor.so
7f4212840000-7f4212841000 r--p 00002000 103:01 4976912                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/monitor.so
7f4212841000-7f4212842000 r--p 00002000 103:01 4976912                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/monitor.so
7f4212842000-7f4212843000 rw-p 00003000 103:01 4976912                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/monitor.so
7f4212843000-7f4212844000 r--p 00000000 103:01 4976861                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/trans/transdb.so
7f4212844000-7f4212846000 r-xp 00001000 103:01 4976861                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/trans/transdb.so
7f4212846000-7f4212847000 r--p 00003000 103:01 4976861                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/trans/transdb.so
7f4212847000-7f4212848000 r--p 00003000 103:01 4976861                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/trans/transdb.so
7f4212848000-7f4212849000 rw-p 00004000 103:01 4976861                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/trans/transdb.so
7f4212849000-7f421284a000 r--p 00000000 103:01 4976879                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/encdb.so
7f421284a000-7f421284b000 r-xp 00001000 103:01 4976879                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/encdb.so
7f421284b000-7f421284c000 r--p 00002000 103:01 4976879                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/encdb.so
7f421284c000-7f421284d000 r--p 00002000 103:01 4976879                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/encdb.so
7f421284d000-7f421284e000 rw-p 00003000 103:01 4976879                   /home/bento/.rbenv/versions/3.2.2/lib/ruby/3.2.0/x86_64-linux/enc/encdb.so
7f421284e000-7f4212855000 r--s 00000000 103:01 3794                      /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f4212855000-7f4212857000 rw-p 00000000 00:00 0
7f4212857000-7f4212858000 r--p 00000000 103:01 4758                      /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f4212858000-7f421287b000 r-xp 00001000 103:01 4758                      /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f421287b000-7f4212883000 r--p 00024000 103:01 4758                      /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f4212884000-7f4212885000 r--p 0002c000 103:01 4758                      /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f4212885000-7f4212886000 rw-p 0002d000 103:01 4758                      /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f4212886000-7f4212887000 rw-p 00000000 00:00 0
7fffbac5f000-7fffbb45e000 rw-p 00000000 00:00 0                          [stack]
7fffbb4f9000-7fffbb4fd000 r--p 00000000 00:00 0                          [vvar]
7fffbb4fd000-7fffbb4ff000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]

**Comment by tonywok** [comment]
I released a new .zip of the koans. Would you be able to see if this resolves your issue?

**Comment by tonywok** [comment]
Closing as duplicate. Thank you for the detailed error message.
